momentohq/client-sdk-java

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
There are some material changes in io.grpc netty methods that don't
work well with the older versions in here. No reason not to use the
newer versions we've tested on the service.
Integration tests pass locally against a momento endpoint.
=> chore: upgrade antique dependencies

.github/workflows/ci.yml
identical pr to https://github.com/momentohq/client-sdk-javascript/pull/100
ensures that every commit shows up in the release
=> chore: add shared build step in ci.yaml

build.gradle.kts, momento-sdk/build.gradle.kts
we don't depend on anything other than otel apis in our implementation.
we should not have such a wide runtimeDependency closure as to take an
opinion about (e.g.) the exporter
=> chore: fix otel dependencies

momento-sdk/build.gradle.kts, momento-sdk/src/intTest/java/momento/sdk/SimpleCacheClientTest.java, momento-sdk/src/intTest/java/momento/sdk/SimpleCacheDataPlaneAsyncTest.java, momento-sdk/src/intTest/java/momento/sdk/SimpleCacheDataPlaneBlockingTest.java, momento-sdk/src/intTest/java/momento/sdk/TestUtils.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/SimpleCacheClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheGetResponse.java
Update the response returned by the get and getAsync methods to match the pattern we have established in other SDKs. The response has three implementations: Hit, Miss, and Error, and it no longer throws. It is intended to be used with pattern matching.
Change the deleteAsync method to delete instead of getting.
Add a test dependency on AssertJ, a neat fluent assertion library.
=> chore: update getCache response

build.gradle.kts, gradle/libs.versions.toml, momento-sdk/build.gradle.kts
Move dependency versions into a gradle catalog in libs.versions.toml.
Switch to the newest version of client-protos.
Switch jjwt-jackson to jjwt-gson because we already have a dependency on gson.
Update misc dependencies.
=> chore: update sdk dependencies

gradle/libs.versions.toml, momento-sdk/build.gradle.kts, momento-sdk/src/main/java/momento/sdk/ScsControlClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/exceptions/AlreadyExistsException.java, momento-sdk/src/main/java/momento/sdk/exceptions/CacheServiceExceptionMapper.java, momento-sdk/src/main/java/momento/sdk/exceptions/NotFoundException.java, momento-sdk/src/main/java/momento/sdk/exceptions/TimeoutException.java, momento-sdk/src/main/java/momento/sdk/internal/MomentoGrpcErrorDetails.java
Switch from a custom metadata object to the grpc class to match with the other sdks.
Make grpc-api an api dependency because several of its classes are exposed through the sdk's exceptions.
Clean up some non-final variables.
=> chore: use grpc metadata in errors

momento-sdk/src/intTest/java/momento/sdk/CacheClientTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSetIfNotExistsResponse.java
- Add support for setIfNotExists API for
- {String} key, {String} value
- {String} key, {Byte Array} value, 
- {Byte Array} key, {String} value
- {Byte Array} key, {Byte Array} value
- `./gradlew :momento-sdk:spotlessApply && ./gradlew clean build`
#154
=> chore: Add support for setIfNotExists API

gradle/libs.versions.toml, momento-sdk/build.gradle.kts, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/CacheClientBuilder.java, momento-sdk/src/main/java/momento/sdk/ScsControlClient.java, momento-sdk/src/main/java/momento/sdk/ScsControlGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataGrpcStubsManager.java
Remove member variable and method argument optionals. Java optionals are sad compared to Kotlin's and provide no null guarantees, so it is valid to supply a method that takes an optional with a null.
Add a jsr305 dependency to get access to @Nonnull and @Nullable annotations.
Annotate the cache client constructor chain with @Nullable and @Nonnull. These are the only places where the sdk can throw an exception if nulls are provided.
Fix a few misc warnings.
=> chore: Remove member variable optionals and fix warnings

buildSrc/src/main/kotlin/momento.publishable-java-lib.gradle.kts
Switch signing and publishing blocks to fix publishing failure when the signing plugin is used.
=> fix: fix publishing not working for signed artifacts

momento-sdk/src/intTest/java/momento/sdk/SetTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/ValidationUtils.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSetAddElementResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSetFetchResponse.java, momento-sdk/src/main/java/momento/sdk/requests/CollectionTtl.java
Add setAddElement methods for string and byte[] elements.
Add setFetch.
Make seconds and milliseconds methods in CollectionTtl return Optionals because the internal ttl may be null.
=> feat: Add setAddElement and setFetch methods

momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheListConcatenateFrontResponse.java
- Add CacheListConcatenateFront API
- Refactor CacheListConcatenateBack to match the front api
- Add/Refactor integ tests
- Fix Integer to int for truncateFrontToSize & TruncateBackToSize
- As a result of above, had to split the String and ByteArray function names to avoid methods with same erasure exception
- Add tests to validate that same list can be added to front/back of the list
#170
=> feat: Add CacheListConcatenateFront API

momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java
- Add method signatures that do not take ttl for list collections
- Refactor related integ tests
#170, #201
=> feat: Add method signatures that do not take ttl for list collections

momento-sdk/src/intTest/java/momento/sdk/CacheClientTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java
1. Hanlde null ttl in method signatures for:
- set mthods
- increment methods
- setIfNotExists methods
1. Add integ tests for when ttl is not specified for 
- increment methods
- setIfNotExists methods
#203
=> fix: Hanlde null ttl in method signatures

momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java
- Update method signatures to have ttl as the last parameter for list collection APIs
- Call the sdsDataClient methods from cacheClient methods that do not have ttl specified as one of the parameters
#204
=> feat: Update method signatures

momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionarySetFieldsResponse.java
- Add dictionarySetFields API
- Had to use different names for methods to avoid "same erasure" problem
- Change implementation from AbstractMap to Map
- Refactor integ tests based on the above change
#171
=> feat: Add dictionarySetFields API

momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryFetchResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheListFetchResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSetFetchResponse.java
- Remove memoization from fetch apis in collections
#171
=> chore: Remove memoization from fetch APIs

momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/intTest/java/momento/sdk/SetTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryFetchResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheListFetchResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSetFetchResponse.java
- remove string suffix
- remove memoization 
- refactor java docs
- rename items to elements to match the method signature in other sdks like .NET
=> fix: remove string suffix, memoization, refactor java docs

momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryGetFieldResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryGetFieldsResponse.java
- Add dictionaryGetFields API
- Add field parameter to CacheDictionaryGetFieldResponse.Error constructor (required for implementing the plural case)
- Remove elements and fields internal representation from response class
- Use the responseList to get the map for desired data types
- fix minor bugs/ addressed comments on commit 1
#171
=> feat: Add didctionaryGetFields API

momento-sdk/src/intTest/java/momento/sdk/BaseTestClass.java, momento-sdk/src/intTest/java/momento/sdk/CacheClientTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheControlPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneClientSideTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/intTest/java/momento/sdk/SetTest.java, momento-sdk/src/intTest/java/momento/sdk/SortedSetTest.java, momento-sdk/src/main/java/momento/sdk/auth/CredentialProvider.java, momento-sdk/src/main/java/momento/sdk/auth/StringCredentialProvider.java
Add fromString and fromEnvVar methods to CredentialProvider.
Change most instances of CredentialProvider in tests to use the new methods.
=> chore: add fromString and fromEnvVar methods to CredentialProvider

momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneClientSideTest.java, momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java
Remove client methods that take a ByteBuffer. They can be added later if desired.
Fix warnings in ScsDataClient.
=> chore: Remove ByteBuffer methods and fix warnings

momento-sdk/src/intTest/java/momento/sdk/SortedSetTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java
Many sorted set APIs alter an element, as indexed by a
`value`. Consistent with other SDKs, we call the argument `value`, not
`element`, since `element` can be confused with the value+score
combination.
work towards https://github.com/momentohq/client-sdk-java/issues/248
=> chore: normalize sorted set api names

momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java
Lift `sortedSetGetScores` and `sortedSetRemoveElements` argument `values` from `Set` to `Iterable`. Generally speaking the service does not impose uniqueness constraints on collection inputs, so a narrow `Set` input is not necessary. A user may pass in any iterable container, which may or may not contain duplicates.
Work towards: https://github.com/momentohq/client-sdk-java/issues/248
=> chore: audit sorted set collection arguments

momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/ValidationUtils.java
The previous validation message for checking the sorted set name was
the message for sets. This fix adds a specific message for sorted sets
to differentiate from the set collection.
=> fix: sorted set name validation message should mention sorted sets

momento-sdk/src/intTest/java/momento/sdk/SortedSetTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java
Adds a `sortedSetFetchByScore` overload which fetches the whole sorted set in ascending order.
work towards: https://github.com/momentohq/client-sdk-java/issues/248
=> feat: add sorted set fetch by score overload to fetch whole set

momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/ValidationUtils.java
Make the truncate*ToSize arguments in the internal client nullable.
Annotate all list method arguments Nullable/Nonnull in the internal
client.
Add validation to ensure the truncate*ToSize arguments are greater than
0. Fix the tests that were supplying 0.
Make the list methods that take a List<> take an Iterable<>.
Fix warnings in the list rpc request generation code.
=> chore: Update list internal methods with nullable truncate*ToSize

momento-sdk/src/intTest/java/momento/sdk/SortedSetTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java
Until a future ask comes in, we will suppose the following overloads
for `sortedSetFetchByScore`:
- (nothing) fetch the whole sorted set
- (common options) minScore, maxScore, sortOrtder
- (all options) minScore, maxScore, sortOrder, limit, offset
work towards: https://github.com/momentohq/client-sdk-java/issues/248
=> chore: pare down `sortedSetFetchByScore` overloads

momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryFetchResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryGetFieldResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryGetFieldsResponse.java
Remove all dictionary methods that take byte[] as a field. byte[] does not behave well as a map key. We can add them back in later if desired.
Remove dictionary response getters that return byte[] fields.
Move grpc-specific logic from dictionary responses into the internal client.
=> chore: Remove dictionary methods that take byte[] fields

.github/workflows/ci.yml
Prevent collisions between concurrent CI workflows.
=> fix: use unique prefix for CI test cache names

.github/workflows/manual-release.yml
Rename CD job to Manual Release to reflect what it does.
Remove development versions flag from the version action to allow for a 1.0 release.
=> chore: Prepare job for 1.0 release

.github/workflows/manual-release.yml
We are generating the README on push to main so we don't need
it on the release task anymore, and this version is outdated.
=> chore: remove README generator action from manual release task

examples/cache/build.gradle.kts, examples/cache/src/main/java/momento/client/example/LoadGenerator.java
Add a load generator example in the style of load generators we've made for other SDKs. It schedules a configurable number of alternating write and read tasks, limiting the total tps using a Guava RateLimiter.
=> feat: Add a load generator to the examples

gradle/libs.versions.toml, momento-sdk/build.gradle.kts, momento-sdk/src/intTest/java/momento/sdk/CacheControlPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneTest.java, momento-sdk/src/intTest/resources/logback.xml, momento-sdk/src/main/java/momento/sdk/CacheClientBuilder.java, momento-sdk/src/main/java/momento/sdk/RetryClientInterceptor.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/config/Configuration.java, momento-sdk/src/main/java/momento/sdk/config/Configurations.java, momento-sdk/src/main/java/momento/sdk/retry/DefaultRetryEligibilityStrategy.java, momento-sdk/src/main/java/momento/sdk/retry/FixedCountRetryStrategy.java, momento-sdk/src/main/java/momento/sdk/retry/FixedDelayRetryStrategy.java, momento-sdk/src/main/java/momento/sdk/retry/RetryEligibilityStrategy.java, momento-sdk/src/main/java/momento/sdk/retry/RetryStrategy.java, momento-sdk/src/main/java/momento/sdk/retry/RetryingUnaryClientCall.java, momento-sdk/src/test/java/momento/sdk/retry/FixedCountRetryStrategyTest.java, momento-sdk/src/test/java/momento/sdk/retry/FixedDelayRetryStrategyTest.java
Apart from adding retries, this PR contains backward incompatible changes with respect to cache client initialization. We made this decision as the SDK is relatively young and to follow better and consistent practices with other SDKs. Previously, if a user wanted to override the gRPC request deadline, they did:
```
CacheClient.builder(
credentialProvider, Configurations.Laptop.latest(), DEFAULT_TTL_SECONDS)
.setDeadline(Duration.ofMillis(0))
.build());
```
The `setDeadline` method violates the builder pattern and overrides an already initialized configuration. We also want to remove the word deadline as it's not conventional and gRPC specific. This PR removes `setDeadline` from the builder, and adds a `withTimeout` to the Configuration object which returns a new Configuration object with …
=> feat: add retry interceptor for JAVA SDK

examples/lambda/README.md, examples/lambda/docker/Dockerfile, examples/lambda/docker/build.gradle.kts, examples/lambda/docker/src/main/java/momento/lambda/example/MomentoJavaLambda.java, examples/lambda/infrastructure/.eslintignore, examples/lambda/infrastructure/.eslintrc.json, examples/lambda/infrastructure/.gitignore, examples/lambda/infrastructure/.npmignore, examples/lambda/infrastructure/.prettierrc.json, examples/lambda/infrastructure/bin/infrastructure.ts, examples/lambda/infrastructure/cdk.json, examples/lambda/infrastructure/jest.config.js, examples/lambda/infrastructure/lib/stack.ts, examples/lambda/infrastructure/package-lock.json, examples/lambda/infrastructure/package.json, examples/lambda/infrastructure/tsconfig.json, examples/settings.gradle.kts, momento-sdk/src/intTest/java/momento/sdk/BaseTestClass.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneEagerConnectionTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/config/Configurations.java
This PR adds the following to Java SDK
- Eager connection for both sync client through a new factory method
- Lambda configuration
- Example for Java SDK and AWS Lambda
- This will be updated to use the Lambda configuration created above in the next PR
```
16:30:55.501 [grpc-default-executor-1] INFO  momento.sdk.ScsDataGrpcStubsManager -- State transitioned to CONNECTING; waiting to get READY
16:30:55.815 [grpc-default-executor-0] INFO  momento.sdk.ScsDataGrpcStubsManager -- Connected to Momento's server! Happy Caching!
CacheDataPlaneEagerConnectionTest > getReturnsHitAfterSet() PASSED
BUILD SUCCESSFUL in 3s
```
=> feat: add factory method that eagerly connects with lambda examples

examples/cache/src/main/java/momento/client/example/BatchUtilsExample.java, momento-sdk/src/main/java/momento/sdk/batchutils/MomentoBatchUtils.java
update concurrency level to 20 for batchGet in SDK and examples based on perf test results here  https://github.com/momentohq/dev-eco-issue-tracker/issues/578
=> chore: update concurrency level to 20

CONTRIBUTING.md, examples/gradle/wrapper/gradle-wrapper.properties, examples/settings.gradle.kts, momento-sdk/src/main/java/momento/sdk/auth/EnvVarCredentialProvider.java
This commit adds a bit more error handling to the EnvVarCredentialProvider so that if the
environment variable is missing, we will give a slightly more helpful error message.
Also includes a commented-out gradle snippet for the examples project which allows you to
compile the examples against your local copy of the SDK, so that it is easier to test changes
as you are developing.
=> chore: improve missing env var message, illustrate how to build examples against local SDK

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/manual-release.yml, .github/workflows/on-push-to-main-branch.yml
Using a special private token to checkout our repo is not a realistic way a customer may checkout our repo. I think this might be an artifact stemming from when we were using git submodules
=> fix: don't checkout repo with private token inside of ci

momento-sdk/src/main/java/momento/sdk/IScsTopicConnection.java, momento-sdk/src/main/java/momento/sdk/ISubscriptionCallbacks.java, momento-sdk/src/main/java/momento/sdk/ScsTopicClient.java, momento-sdk/src/main/java/momento/sdk/SendSubscribeOptions.java, momento-sdk/src/main/java/momento/sdk/SubscriptionWrapper.java, momento-sdk/src/test/java/momento/sdk/SubscriptionWrapperTest.java, momento-sdk/src/test/resources/logback.xml
-  add onConnectionLost and onConnectionRestored callback functions
- make them default so that the user is not compelled to implement the functions 
- Run TopicExample in the examples/topics directory
- Switch off the wifi in the middle of messages being published
- Wait for the server to throw an exception (UNAVAILABLE) exception
- Switch on the wifi
- Verify logging statements in the default `onConnectionLost` and default `onConnectionRestored` are invoked
- `SubscriptionWrapperTest` in unit tests.
=> feat: add onConnectionLost and onConnectionRestored callback functions

momento-sdk/src/main/java/momento/sdk/ScsDataGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/config/Configuration.java, momento-sdk/src/main/java/momento/sdk/config/transport/GrpcConfiguration.java
Prior to this commit, each instance of the CacheClient would always
open a single gRPC channel to the server. This commit adds a configuration
setting on the GrpcConfiguration object which allows a user to configure
a minimum number of channels; this is useful for cases where callers will
be issuing more than 100 concurrent requests, since 100 is the maximum
number of requests that can be multiplexed over a single channel.
=> feat: add support for configuring minimum num gRPC channels on CacheClient

.gitignore, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsControlClient.java, momento-sdk/src/main/java/momento/sdk/ScsControlGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ScsDataGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ScsTokenGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ScsTopicGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/config/Configurations.java, momento-sdk/src/main/java/momento/sdk/config/TopicConfigurations.java, momento-sdk/src/main/java/momento/sdk/config/transport/GrpcConfiguration.java, momento-sdk/src/main/java/momento/sdk/internal/GrpcChannelOptions.java, momento-sdk/src/test/java/momento/sdk/Configurations.java
Adds message size to support messages up to 5mb by default (though I was only able to find the max receive message size option through the [NettyChannelBuilder](https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettyChannelBuilder.html#maxInboundMessageSize(int)) interface).
Adds keepalive settings to the configs as well. Disables keepalive for the cache control client and the Lambda prebuilt config. Sets different keepalive values for the topics prebuilt configs based on the values that were hardcoded into the topic grpc manager.
=> feat: add grpc config options and turn off keepalive for Lambda config

examples/cache/src/main/java/momento/client/example/LoadGenerator.java
Have edited load-gens a couple times locally for cancelled might as well commit it
=> chore: add cancelled errors to load-gen

momento-sdk/src/intTest/java/momento/sdk/storage/ControlTests.java, momento-sdk/src/main/java/momento/sdk/StorageControlClient.java, momento-sdk/src/main/java/momento/sdk/StorageDataClient.java, momento-sdk/src/main/java/momento/sdk/exceptions/CacheServiceExceptionMapper.java, momento-sdk/src/main/java/momento/sdk/exceptions/StoreItemNotFoundException.java, momento-sdk/src/main/java/momento/sdk/exceptions/StoreNotFoundException.java
This PR detects when a `NOT_FOUND` gRPC error was specific to the
storage client or not. For the storage client `NOT_FOUND`, there are
two cases: the store was not found and the item was not found.
To distinguish these two cases we use string matching on the
grpcException message.
=> refactor: introduce `Store(Item)?NotFoundException` classes

momento-sdk/src/intTest/java/momento/sdk/CacheClientTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheControlPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/SortedSetTest.java, momento-sdk/src/intTest/java/momento/sdk/storage/DataTests.java, momento-sdk/src/main/java/momento/sdk/StorageControlClient.java, momento-sdk/src/main/java/momento/sdk/exceptions/AlreadyExistsException.java, momento-sdk/src/main/java/momento/sdk/exceptions/CacheAlreadyExistsException.java, momento-sdk/src/main/java/momento/sdk/exceptions/CacheNotFoundException.java, momento-sdk/src/main/java/momento/sdk/exceptions/CacheServiceExceptionMapper.java, momento-sdk/src/main/java/momento/sdk/exceptions/NotFoundException.java, momento-sdk/src/main/java/momento/sdk/exceptions/StoreAlreadyExistsException.java, momento-sdk/src/test/java/momento/sdk/responses/storage/GetResponseTest.java
Refactors `NotFoundException` and `AlreadyExistsException` to cache- and storage-specific exceptions.
=> refactor: specialize not-found and already-exists exceptions

momento-sdk/src/main/java/momento/sdk/responses/storage/GetResponse.java, momento-sdk/src/main/java/momento/sdk/responses/storage/ListStoresResponse.java, momento-sdk/src/main/java/momento/sdk/responses/storage/StorageValue.java, momento-sdk/src/main/java/momento/sdk/responses/storage/StoreInfo.java
`GetResponse` and `ListStoresResponse` should have meaningful to
string implementations. This PR adds them.
=> chore: add to string implementations to relevant storage responses

momento-sdk/src/main/java/momento/sdk/exceptions/CacheServiceExceptionMapper.java
Consumes the server metadata change from `element_not_found` to `item_not_found`.
=> fix: use server metadata for item not found

momento-sdk/src/intTest/java/momento/sdk/storage/DataTests.java, momento-sdk/src/main/java/momento/sdk/exceptions/CacheServiceExceptionMapper.java
Update the client to read `store_not_found` metadata to distinguish
cache vs store not found. Use `StoreNotFoundException` in tests.
=> fix: use store_not_found metadata and appropriate exceptions

momento-sdk/src/intTest/java/momento/sdk/storage/ControlTests.java, momento-sdk/src/main/java/momento/sdk/exceptions/SdkException.java, momento-sdk/src/main/java/momento/sdk/internal/MomentoGrpcErrorDetails.java, momento-sdk/src/main/java/momento/sdk/internal/MomentoTransportErrorDetails.java, momento-sdk/src/main/java/momento/sdk/internal/StringHelpers.java, momento-sdk/src/main/java/momento/sdk/responses/storage/CreateStoreResponse.java, momento-sdk/src/main/java/momento/sdk/responses/storage/DeleteResponse.java, momento-sdk/src/main/java/momento/sdk/responses/storage/DeleteStoreResponse.java, momento-sdk/src/main/java/momento/sdk/responses/storage/GetResponse.java, momento-sdk/src/main/java/momento/sdk/responses/storage/ListStoresResponse.java, momento-sdk/src/main/java/momento/sdk/responses/storage/PutResponse.java, momento-sdk/src/main/java/momento/sdk/responses/storage/StorageValue.java, momento-sdk/src/main/java/momento/sdk/responses/storage/StoreInfo.java
Refactors the `toString` implementations to depart from the cache
client pattern. Ensures human readable `toString`s across the board,
adds helpers for trivial `toString`s and error-type `toString`s.
(error message will be adjusted later)
=> refactor: make storage to string more human friendly

momento-sdk/src/main/java/momento/sdk/PreviewStorageClientBuilder.java
Adds a storage client builder for convenience. The default status of
credential provider and the configuration are subject to change.
=> chore: add storage client builder

momento-sdk/src/main/java/momento/sdk/PreviewStorageClientBuilder.java
In order to offer both convenience and best experience for users, we
warn on using the laptop config in production.
=> chore: warn on storage client builder use of laptop config in prod

momento-sdk/src/main/java/momento/sdk/ScsControlClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/StorageDataClient.java, momento-sdk/src/main/java/momento/sdk/exceptions/CacheServiceExceptionMapper.java
Because the gRPC status exception contains the response metadata, the
cache exception mapper should read the metadata from there. Previously
we re-used the request metadata, which lacked the server-side
processing details.
=> fix: cache service exception mapper should read metadata from exc

momento-sdk/src/intTest/java/momento/sdk/storage/DataTests.java, momento-sdk/src/main/java/momento/sdk/StorageDataClient.java, momento-sdk/src/main/java/momento/sdk/responses/storage/GetResponse.java, momento-sdk/src/main/java/momento/sdk/responses/storage/GetResponseFound.java, momento-sdk/src/main/java/momento/sdk/responses/storage/StorageValue.java, momento-sdk/src/main/java/momento/sdk/utils/MomentoOptional.java, momento-sdk/src/test/java/momento/sdk/responses/storage/GetResponseTest.java
1. Split `GetResponse.Success` into `GetResponse.Found` and, in the event the item isn't found, `GetResponse.NotFound`. This sheds the optional on `value`.
2. Add a `valueWhenFound` shortcut accessor on the interface that returns a `MomentoOptional<StorageValue>`.
3. ~~Throw exceptions when `StorageValue::get*` are called on the wrong type. This sheds the `Optional` on those responses.~~ Return a `MomentoOptional` which allows for both optional behavior and custom error messages. A careful user can still switch on `StorageValue::getType` for exhaustiveness checks.
4. ~~Add `GetResponse::asFound` which returns `GetResponseFound` in the event of a `GetResponse.Found` otherwise throws an exception.~~ Will add this on demand per user feedback in order to keep the API slim.
5. Introduce …
=> feat: storage get response 2.0

momento-sdk/src/intTest/java/momento/sdk/AuthClientCacheTests.java, momento-sdk/src/intTest/java/momento/sdk/AuthClientTopicTests.java, momento-sdk/src/intTest/java/momento/sdk/BaseTestClass.java, momento-sdk/src/intTest/java/momento/sdk/CacheClientTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheControlPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneClientSideTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneEagerConnectionTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/intTest/java/momento/sdk/MomentoBatchUtilsIntegrationTest.java, momento-sdk/src/intTest/java/momento/sdk/SetTest.java, momento-sdk/src/intTest/java/momento/sdk/SortedSetTest.java, momento-sdk/src/intTest/java/momento/sdk/TestUtils.java, momento-sdk/src/intTest/java/momento/sdk/TopicClientTest.java
Refactors the cache and topics integration tests to use a random cache
name instead of reading from the environment. This follows the
JavaScript SDK pattern.
We have re-written the tests to use a base test class that sets up the
client, assigns a random cache name, creates the cache, and tears it
down at the end of tests.
Because a test class now re-uses the same cache, we have refactored
the tests to use random keys in each test case. These two changes have
fixed race conditions that have caused consistent test failures when
running locally.
Lastly the auth tests were not closing clients in the tests. Because
of this, warning messages appeared in the logs consistently. We have
fixed these problems by closing clients between reuse.
=> refactor: java cache and topics integration tests should use random cache names

momento-sdk/src/intTest/java/momento/sdk/BaseStorageTestClass.java, momento-sdk/src/intTest/java/momento/sdk/storage/ControlTests.java, momento-sdk/src/intTest/java/momento/sdk/storage/DataTests.java, momento-sdk/src/main/java/momento/sdk/PreviewStorageClientBuilder.java
Refactors the storage tests to use a base class similar to the one
just introduced for cache. Handles store set up and tear down uniformly.
=> refactor: storage tests should use a single test store and base

momento-sdk/src/intTest/java/momento/sdk/AuthClientCacheTests.java, momento-sdk/src/intTest/java/momento/sdk/AuthClientTopicTests.java, momento-sdk/src/intTest/java/momento/sdk/BaseCacheTestClass.java, momento-sdk/src/intTest/java/momento/sdk/BaseStorageTestClass.java, momento-sdk/src/intTest/java/momento/sdk/CacheClientTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheControlPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneClientSideTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneEagerConnectionTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/intTest/java/momento/sdk/MomentoBatchUtilsIntegrationTest.java, momento-sdk/src/intTest/java/momento/sdk/SetTest.java, momento-sdk/src/intTest/java/momento/sdk/SortedSetTest.java, momento-sdk/src/intTest/java/momento/sdk/TopicClientTest.java, momento-sdk/src/intTest/java/momento/sdk/storage/ControlTests.java, momento-sdk/src/intTest/java/momento/sdk/storage/DataTests.java, momento-sdk/src/main/java/momento/sdk/PreviewStorageClientBuilder.java
Renames the cache `BaseTestClass` to `BaseCacheTestClass` for clarity.
=> refactor: rename cache test base

Makefile, momento-sdk/src/intTest/java/momento/sdk/storage/DataTests.java, momento-sdk/src/main/java/momento/sdk/responses/storage/StorageValue.java, momento-sdk/src/main/java/momento/sdk/utils/MomentoOptional.java, momento-sdk/src/test/java/momento/sdk/responses/storage/GetResponseTest.java
The `orElseThrow` signature of Java Optionals requires a single
arg, `supplier`, that is a lambda function returning the exception
that the user wishes to have thrown if the optional is empty.
In our current storage client code we have an empty-args signature,
which would be surprising to Java users familiar with Optionals.
This commit updates the signature to accept a supplier.
=> fix: storage SDK orElseThrow should take a supplier

momento-sdk/src/intTest/java/momento/sdk/storage/DataTests.java, momento-sdk/src/main/java/momento/sdk/exceptions/CacheServiceExceptionMapper.java
Stop looking at error metadata to determine whether an already exists error is for a store or cache. We can check it when that is added on the server side.
Update a test that was checking that the server could support empty keys in the store client. That changed on the server side.
=> fix: fix failing storage tests

momento-sdk/src/main/java/momento/sdk/CacheClient.java
Corrects the end index documentation on `listFetch` to indicate it is
exclusive, not inclusive.
=> docs: fix list fetch end index description

momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/ValidationUtils.java
Adds various overloads for cache `listFetch`,
`listConcatenateFrontByteArray`, and `listRetain` for the `listName`
as a byte array.
=> feat: add byte array for list methods on the list name

momento-sdk/src/main/java/momento/sdk/ScsControlGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ScsDataGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ScsTokenGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ScsTopicGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/StorageControlGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/StorageDataGrpcStubsManager.java
Set stub deadlines using milliseconds instead of seconds. Duration.getSeconds() truncates, so a client configuration with a timeout of less than one second, like the preconfigured LowLatency config, always has a deadline of 0, so no calls will ever succeed.
Remove the documentation from the topic stubs manager that states that it sets a deadline on the stub it returns.
=> fix: set stub deadlines using millis instead of seconds

momento-sdk/src/intTest/java/momento/sdk/CacheClientTest.java, momento-sdk/src/main/java/momento/sdk/ClientBase.java, momento-sdk/src/main/java/momento/sdk/ScsClientBase.java, momento-sdk/src/main/java/momento/sdk/ScsControlClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/ScsTopicClient.java, momento-sdk/src/main/java/momento/sdk/StorageClientBase.java, momento-sdk/src/main/java/momento/sdk/StorageControlClient.java, momento-sdk/src/main/java/momento/sdk/StorageDataClient.java, momento-sdk/src/main/java/momento/sdk/config/transport/StaticTransportStrategy.java, momento-sdk/src/main/java/momento/sdk/config/transport/TransportStrategy.java
Adds concurrency limiting to the base client class in the style of https://github.com/momentohq/client-sdk-java/pull/385.
The concurrency limiting function is almost the same as the prototype and wraps the existing generic `executeGrpcFunction` and `executeGrpcBatchFunction` methods.
The PR is broken up into 3 commits:
The first adds the concurrency limiting fixed thread pool to the base client class, along with the constructor to configure it and the `close()` method to shut it down. It replaces the `close()` in the child classes with a new abstract `doClose()` so that there is still a close that the children are forced to implement.
The second adds the max concurrent requests integer to the transport strategy layer of the config and plumbs it through the cache data and control clients …
=> feat: Concurrency limiter

momento-sdk/src/main/java/momento/sdk/exceptions/CacheServiceExceptionMapper.java, momento-sdk/src/main/java/momento/sdk/exceptions/LimitExceededException.java, momento-sdk/src/main/java/momento/sdk/exceptions/LimitExceededMessageWrapper.java
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1052
Adds a factory method for `LimitExceededException` that takes in an error cause (`err` metadata or grpc error details string) and constructs a `LimitExceededException` with a message wrapper that includes the limit that was exceeded.
=> chore: improve resource exhausted error message

momento-sdk/src/main/java/momento/sdk/RetryClientInterceptor.java, momento-sdk/src/main/java/momento/sdk/retry/DefaultRetryEligibilityStrategy.java, momento-sdk/src/main/java/momento/sdk/retry/RetryingClientCall.java
- This PR updates the RetryInterceptor to handle retries for both unary and streaming calls (e.g., getBatch) without requiring any code changes to the interceptor itself. The existing logic in RetryInterceptor uses the following condition to determine if a call should be retried:
```
if (!method.getType().clientSendsOneMessage()) {
return channel.newCall(method, callOptions);
}
```
This leverages the method.getType().clientSendsOneMessage() check, where:
```
public final boolean clientSendsOneMessage() {
return this == UNARY || this == SERVER_STREAMING;
}
```
Since both unary and server-side streaming calls return true for `clientSendsOneMessage()`, the existing interceptor logic is inherently compatible with server-side streaming calls. To enable retries for `getBatch` specifically, this …
=> feat: use retry interceptor for streaming calls

.github/workflows/ci.yml, Makefile, momento-sdk/build.gradle.kts, momento-sdk/src/intTest/java/momento/sdk/BaseCacheTestClass.java, momento-sdk/src/intTest/java/momento/sdk/CacheControlPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/MomentoBatchUtilsIntegrationTest.java, momento-sdk/src/intTest/java/momento/sdk/auth/AuthClientCacheTests.java, momento-sdk/src/intTest/java/momento/sdk/auth/AuthClientTopicTests.java, momento-sdk/src/intTest/java/momento/sdk/cache/BaseCacheTestClass.java, momento-sdk/src/intTest/java/momento/sdk/cache/CacheClientTest.java, momento-sdk/src/intTest/java/momento/sdk/cache/CacheControlPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/cache/CacheDataPlaneClientSideTest.java, momento-sdk/src/intTest/java/momento/sdk/cache/CacheDataPlaneEagerConnectionTest.java, momento-sdk/src/intTest/java/momento/sdk/cache/CacheDataPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/cache/DictionaryTest.java, momento-sdk/src/intTest/java/momento/sdk/cache/ListTest.java, momento-sdk/src/intTest/java/momento/sdk/cache/SetTest.java, momento-sdk/src/intTest/java/momento/sdk/cache/SortedSetTest.java, momento-sdk/src/intTest/java/momento/sdk/storage/BaseStorageTestClass.java, momento-sdk/src/intTest/java/momento/sdk/storage/ControlTests.java, momento-sdk/src/intTest/java/momento/sdk/storage/DataTests.java, momento-sdk/src/intTest/java/momento/sdk/topics/TopicClientTest.java, momento-sdk/src/main/java/momento/sdk/ScsDataGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/UserHeaderInterceptor.java, momento-sdk/src/main/java/momento/sdk/config/Configuration.java, momento-sdk/src/main/java/momento/sdk/config/ReadConcern.java
Add the read concern option to the cache Configuration and thread it through to the gRPC internals of the client.
Add an argument to the UserHeaderInterceptor constructor representing a list of extra headers to add to every request. The stubs manager uses this to add the read concern header if it isn't set to balanced.
Make the base cache test class create clients with both balanced and consistent read concern, and set the cache client used by all the tests to the consistent one if the CONSISTENT_READS env var is defined.
Add tasks to run integration tests for the different clients.
Add make targets to use the new tasks.
=> feat: add the read concern header

momento-sdk/src/main/java/momento/sdk/config/transport/GrpcConfiguration.java, momento-sdk/src/main/java/momento/sdk/config/transport/IGrpcConfiguration.java, momento-sdk/src/main/java/momento/sdk/config/transport/storage/StorageGrpcConfiguration.java, momento-sdk/src/main/java/momento/sdk/internal/GrpcChannelOptions.java
Add an interface for GrpcConfigration so that common code for setting up connections can work with the different implementations.
Update the applyGrpcConfigurationToChannelBuilder logic to work with IGrpcConfigration and reduce the two implementations to one.
=> chore: Add a gRPC configuration interface

Makefile, momento-sdk/build.gradle.kts, momento-sdk/src/intTest/java/momento/sdk/leaderboard/BaseLeaderboardTestClass.java, momento-sdk/src/intTest/java/momento/sdk/leaderboard/LeaderboardClientTest.java, momento-sdk/src/main/java/momento/sdk/ILeaderboard.java, momento-sdk/src/main/java/momento/sdk/Leaderboard.java, momento-sdk/src/main/java/momento/sdk/LeaderboardClient.java, momento-sdk/src/main/java/momento/sdk/LeaderboardClientBuilder.java, momento-sdk/src/main/java/momento/sdk/LeaderboardDataClient.java, momento-sdk/src/main/java/momento/sdk/LeaderboardGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ValidationUtils.java, momento-sdk/src/main/java/momento/sdk/config/LeaderboardConfiguration.java, momento-sdk/src/main/java/momento/sdk/config/LeaderboardConfigurations.java, momento-sdk/src/main/java/momento/sdk/config/transport/leaderboard/LeaderboardGrpcConfiguration.java, momento-sdk/src/main/java/momento/sdk/config/transport/leaderboard/LeaderboardTransportStrategy.java, momento-sdk/src/main/java/momento/sdk/config/transport/leaderboard/StaticLeaderboardTransportStrategy.java, momento-sdk/src/main/java/momento/sdk/responses/leaderboard/FetchResponse.java, momento-sdk/src/main/java/momento/sdk/responses/leaderboard/LeaderboardElement.java, momento-sdk/src/main/java/momento/sdk/responses/leaderboard/RemoveElementsResponse.java, momento-sdk/src/main/java/momento/sdk/responses/leaderboard/UpsertResponse.java
Add a new client for interacting with Momento leaderboards and the configuration objects required for creating one.
Add the leaderboard upsert, fetch by rank, and remove elements methods.
=> feat: Add leaderboard upsert, fetch by rank, and remove elements

momento-sdk/src/main/java/momento/sdk/responses/cache/ttl/ItemGetTtlResponse.java
Remove a non-ASCII character from a javadoc comment that was preventing the canary docker image from building.
=> fix: update a comment that fails the build in some instances

momento-sdk/src/intTest/java/momento/sdk/leaderboard/LeaderboardClientTest.java, momento-sdk/src/main/java/momento/sdk/ILeaderboard.java, momento-sdk/src/main/java/momento/sdk/Leaderboard.java, momento-sdk/src/main/java/momento/sdk/LeaderboardDataClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/ValidationUtils.java, momento-sdk/src/main/java/momento/sdk/config/transport/leaderboard/LeaderboardGrpcConfiguration.java, momento-sdk/src/main/java/momento/sdk/internal/GrpcChannelOptions.java, momento-sdk/src/main/java/momento/sdk/responses/leaderboard/DeleteResponse.java, momento-sdk/src/main/java/momento/sdk/responses/leaderboard/LengthResponse.java
Add leaderboard fetchByRank, getRank, length, and delete APIs.
Set the default leaderboard max received message size to 200MB.
Make SortOrder in fetchByRank nullable and have it default to ascending if null.
Make the different null check validation methods use the same backing validateNotNull.
=> feat: add the remaining leaderboard APIs

examples/leaderboard/src/main/java/momento/client/example/doc_examples/DocExamplesJavaAPIs.java
Remove arguments from the leaderboard docs example methods that were causing the method signature to be broken up over multiple lines. The extra lines are visible in the docs snippets and are confusing.
=> chore: fix leaderboard docs examples formatting

momento-sdk/src/main/java/momento/sdk/ScsControlGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ScsDataGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/auth/CredentialProvider.java, momento-sdk/src/main/java/momento/sdk/auth/MomentoLocalProvider.java, momento-sdk/src/main/java/momento/sdk/auth/StringCredentialProvider.java, momento-sdk/src/main/java/momento/sdk/internal/GrpcChannelOptions.java, momento-sdk/src/test/java/momento/sdk/auth/MomentoLocalProviderTest.java
- Implement `MomentoLocalProvider`for momento local. 
<details close>
<summary>Tested using the following Java program:</summary>
```
public class Program {
public static void main(String[] args) {
String cacheName = "test-cache-java";
CredentialProvider credentialProvider = new MomentoLocalProvider("0.0.0.0", 8080);
Configuration configuration = Configurations.Laptop.latest();
CacheClient cacheClient =
new CacheClientBuilder(credentialProvider, configuration, Duration.ofMinutes(1)).build();
CacheCreateResponse createResponse = cacheClient.createCache(cacheName).join();
if (createResponse instanceof CacheCreateResponse.Success) {
System.out.println("Cache created successfully");
} else {
System.out.println("Failed to create cache" + createResponse.toString());
CacheCreateResponse.Error …
```
=> feat: implement momento local provider for momento local

momento-sdk/src/intTest/java/momento/sdk/retry/BaseCacheRetryTestClass.java, momento-sdk/src/intTest/java/momento/sdk/retry/TestRetryMetricsCollectorTest.java, momento-sdk/src/intTest/java/momento/sdk/retry/TestRetryMetricsMiddlewareTest.java, momento-sdk/src/intTest/java/momento/sdk/retry/utils/TestRetryMetricsCollector.java, momento-sdk/src/intTest/java/momento/sdk/retry/utils/TestRetryMetricsMiddleware.java, momento-sdk/src/intTest/java/momento/sdk/retry/utils/TestRetryMetricsMiddlewareArgs.java, momento-sdk/src/intTest/java/momento/sdk/retry/utils/TestRetryMetricsMiddlewareRequestHandler.java, momento-sdk/src/main/java/momento/sdk/GrpcMiddlewareInterceptor.java, momento-sdk/src/main/java/momento/sdk/ScsDataGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/config/Configuration.java, momento-sdk/src/main/java/momento/sdk/config/middleware/Middleware.java, momento-sdk/src/main/java/momento/sdk/config/middleware/MiddlewareMessage.java, momento-sdk/src/main/java/momento/sdk/config/middleware/MiddlewareMetadata.java, momento-sdk/src/main/java/momento/sdk/config/middleware/MiddlewareRequestHandler.java, momento-sdk/src/main/java/momento/sdk/config/middleware/MiddlewareRequestHandlerContext.java, momento-sdk/src/main/java/momento/sdk/config/middleware/MiddlewareStatus.java, momento-sdk/src/main/java/momento/sdk/exceptions/MomentoErrorCodeMetadataConverter.java, momento-sdk/src/main/java/momento/sdk/retry/MomentoRpcMethod.java, momento-sdk/src/main/java/momento/sdk/retry/MomentoRpcMethodMetadataConverter.java
This commit introduces a middleware interface using `GrpcMiddlewareInterceptor`, enabling custom middleware implementations for enhanced request and response handling.  
- Added `Middleware` interface to allow users to intercept and modify gRPC request and response data.  
- Implemented `GrpcMiddlewareInterceptor` to integrate middleware into the request pipeline.  
To validate this feature, a custom middleware (`MyCustomMiddleware`) was created and tested using a sample program (`Program.java`). The test includes:  
- Creating a cache using `CacheClient`  
- Setting and retrieving a key-value pair  
- Verifying that the middleware correctly logs request and response metadata, payloads, and statuses  
<details>
<summary>MyCustomMiddleware.java</summary>
```java
package momento.sdk;
import …
```
=> feat: add middleware

momento-sdk/src/intTest/java/momento/sdk/retry/BaseCacheRetryTestClass.java, momento-sdk/src/intTest/java/momento/sdk/retry/ExponentialBackoffRetryStrategyIntegTest.java, momento-sdk/src/intTest/java/momento/sdk/retry/FixedDelayRetryStrategyIntegTest.java, momento-sdk/src/main/java/momento/sdk/RetryClientInterceptor.java, momento-sdk/src/main/java/momento/sdk/retry/ExponentialBackoffRetryStrategy.java, momento-sdk/src/test/java/momento/sdk/retry/ExponentialBackoffRetryStrategyTest.java
Add a new retry strategy that waits for a jittered, exponentially increasing time between attempts until the deadline passes.
=> feat: add exponential backoff retry strategy

momento-sdk/src/main/java/momento/sdk/internal/GrpcChannelOptions.java
- Based on the commit [here](https://github.com/googleapis/gax-java/pull/731), dynamic txt lookup for dns resolution flag is disabled by default in grpc-java. 
- This commit explicitly disables it too. 
```
tcpdump: listening on any, link-type PKTAP (Apple DLT_PKTAP), snapshot length 524288 bytes
10.0.0.249.52040 > pd1nsc3.st.vc.shawcable.net.domain: [udp sum ok] 30203+ A? cache.cell-alpha-dev.preprod.a.momentohq.com. (62)
10.0.0.249.55920 > pd1nsc3.st.vc.shawcable.net.domain: [udp sum ok] 62892+ AAAA? cache.cell-alpha-dev.preprod.a.momentohq.com. (62)
pd1nsc3.st.vc.shawcable.net.domain > 10.0.0.249.52040: [udp sum ok] 30203 q: A? cache.cell-alpha-dev.preprod.a.momentohq.com. 1/0/0 cache.cell-alpha-dev.preprod.a.momentohq.com. [1m] A 54.186.170.81 (78)
pd1nsc3.st.vc.shawcable.net.domain > …
```
=> fix: disable dynamic DNS service config

momento-sdk/src/intTest/java/momento/sdk/retry/TopicClientLocalTest.java, momento-sdk/src/main/java/momento/sdk/ScsTopicClient.java, momento-sdk/src/main/java/momento/sdk/SubscriptionWrapper.java, momento-sdk/src/test/java/momento/sdk/SubscriptionWrapperTest.java
- Enforces deadline on subscribe: Sets a deadline for receiving the first message when subscribing to a topic.
Adds a test case that intentionally delays the subscribe response beyond the client timeout to verify that a TIMEOUT_ERROR is correctly returned.
closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1147
=> feat: add topic subscribe timeout

momento-sdk/src/intTest/java/momento/sdk/retry/TopicClientLocalTest.java
Reduce the client-timeout configuration for the test suite to run faster. 
Follow-up for https://github.com/momentohq/client-sdk-java/pull/437
=> fix: reduce client timeout in topic client momento-local test

momento-sdk/src/intTest/java/momento/sdk/retry/FixedTimeoutRetryStrategyIntegTest.java, momento-sdk/src/intTest/java/momento/sdk/retry/utils/MomentoLocalMiddlewareArgs.java, momento-sdk/src/intTest/java/momento/sdk/retry/utils/MomentoLocalMiddlewareRequestHandler.java, momento-sdk/src/main/java/momento/sdk/RetryClientInterceptor.java
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1207
Assigns the Min(retry deadline, overall deadline) on each retry attempt to ensure we don't exceed the client's overall deadline.
Ended up removing the check for "if retry delay ms will cause retry attempt to exceed client timeout, then don't retry" since that's not included in any other implementations so far. Adjusted one test case to accommodate--depending on jitter, the test may make one retry attempt that will timeout before it can complete.
=> fix: minor fixes for retry tests

momento-sdk/src/intTest/java/momento/sdk/retry/FixedTimeoutRetryStrategyIntegTest.java
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1214
Adds more tests to exercise the retry timeout logic vs momento-local delays. 
Removed one test that didn't seem to properly test the retry timeout stuff.
Seems like the Java retry interceptor + fixed timeout retry strategy is working correctly, so no other bugs to fix in this audit.
=> chore: add more fixed timeout retry strategy tests

build.gradle.kts
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1236
OSSRH is reaching end of life on June 30, 2025, so we migrated our namespace to Sonatype Central namespace.
I think we only need to update the URLs to switch from publishing to OSSRH to Sonatype Central according to these sources [[1](https://github.com/gradle-nexus/publish-plugin?tab=readme-ov-file#publishing-to-maven-central-via-sonatype-central)] [[2](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#plugins-tested-for-compatibility)]
Did a dry-run to confirm the new URLs work
=> chore: replace OSSRH endpoint with Sonatype Central endpoint
