.github/workflows/cd.yml, .github/workflows/ci.yml, README.template.md
https://github.com/momentohq/dev-eco-issue-tracker/issues/109
=> chore: add `README` generator

.gitmodules, momento-sdk/src/intTest/java/momento/sdk/SimpleCacheClientTest.java, momento-sdk/src/main/java/momento/sdk/ScsControlClient.java, momento-sdk/src/main/java/momento/sdk/SimpleCacheClient.java, momento-sdk/src/main/java/momento/sdk/messages/FlushCacheResponse.java
The implementation for exposing the ability to clear the contents of a given cache. All the data set prior to the execution of this API will be lost.
=> feat: Add ability to flush a given cache

momento-sdk/src/intTest/java/momento/sdk/BaseTestClass.java, momento-sdk/src/intTest/java/momento/sdk/SimpleCacheClientTest.java, momento-sdk/src/intTest/java/momento/sdk/SimpleCacheControlPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/SimpleCacheDataPlaneClientSideTest.java, momento-sdk/src/intTest/java/momento/sdk/SimpleCacheDataPlaneTest.java, momento-sdk/src/main/java/momento/sdk/ScsControlClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/SimpleCacheClient.java, momento-sdk/src/main/java/momento/sdk/SimpleCacheClientBuilder.java, momento-sdk/src/main/java/momento/sdk/ValidationUtils.java
- Update ttl from long to duration
- Refactor required integ tests
- Ran `./gradlew :momento-sdk:spotlessApply && ./gradlew clean build` successfully
#174
=> chore: Update ttl from long to duration

.github/dependabot.yml, examples/lib/build.gradle.kts, examples/lib/src/main/java/momento/client/example/MomentoCacheApplication.java, examples/lib/src/main/java/momento/client/example/advanced/MomentoCacheWithDatabase.java
Update dependabot to look for the correct sdk dependency.
Update examples to use new response types.
Change examples to use Java 14 instanceof pattern matching.
=> chore: update example to use released sdk

momento-sdk/src/main/java/momento/sdk/requests/CollectionTtl.java
- Add CollectionTtl for collections apis
- `./gradlew :momento-sdk:spotlessApply && ./gradlew clean build`
#170
=> feat: Add CollectionTtl

momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheListFetchResponse.java
=> chore: Add ListFetch API support

momento-sdk/src/intTest/java/momento/sdk/SetTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSetAddElementsResponse.java
Add setAddStringElements and setAddByteArrayElements methods. They have different names to avoid the method signatures being the same after type erasure.
=> feat: Add setAddElements

momento-sdk/src/main/java/momento/sdk/ScsDataClient.java
Refactor convert functions before sending the list fetch requests
=> chore: Refactor convert functions before sending the list fetch requests

momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheListLengthResponse.java
=> feat: Add list length api support

momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheListPopBackResponse.java
=> feat: Add listPopBack API

momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheListPopFrontResponse.java
=> feat: Add listPopFront API

momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheListPushFrontResponse.java
=> feat: Add listPushFront API

momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheListRemoveValueResponse.java
- Add ListRemoveValue API
#170
=> feat: Add ListRemoveValue API

momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheListRetainResponse.java
=> feat: Add listRetain API

momento-sdk/src/intTest/java/momento/sdk/BaseTestClass.java, momento-sdk/src/intTest/java/momento/sdk/CacheClientTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheControlPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneClientSideTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/intTest/java/momento/sdk/SetTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/CacheClientBuilder.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ValidationUtils.java, momento-sdk/src/main/java/momento/sdk/config/Configuration.java, momento-sdk/src/main/java/momento/sdk/config/Configurations.java, momento-sdk/src/main/java/momento/sdk/config/transport/GrpcConfiguration.java, momento-sdk/src/main/java/momento/sdk/config/transport/StaticTransportStrategy.java, momento-sdk/src/main/java/momento/sdk/config/transport/TransportStrategy.java
Add a configuration object that contains settings for gRPC connections. It will eventually contain retry and middleware configs as well.
Add Laptop, InRegion, and LowLatency default configurations.
=> feat: Add per-environment default configurations

momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryGetFieldResponse.java
- Add dictionaryGetField API
#171
=> feat: Add dictionaryGetField API

momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryIncrementResponse.java
-  Add dictionaryIncrement API
#171
=> feat: Add dictionaryIncrement API

momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryRemoveFieldResponse.java
- Add dictionaryRemoveField API
#171
=> feat: Add dictionaryRemoveField API

momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryRemoveFieldsResponse.java
-  Add dictionaryRemoveFields API
#171
=> feat: Add dictionaryRemoveFields API

momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryFetchResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryGetFieldResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryGetFieldsResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheGetResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheListFetchResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheListPopBackResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheListPopFrontResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSetFetchResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSetIfNotExistsResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSetResponse.java
Add alias for string accessors in response classes
#230
=> chore: Add alias for string accessors in response classes

momento-sdk/src/intTest/java/momento/sdk/SortedSetTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/ValidationUtils.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSortedSetFetchResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSortedSetPutElementResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSortedSetPutElementsResponse.java, momento-sdk/src/main/java/momento/sdk/messages/ScoredElement.java, momento-sdk/src/main/java/momento/sdk/messages/SortOrder.java
Add sortedSetPutElement and sortedSetPutElements.
Add sortedSetFetchByRank and sortedSetFetchByScore.
=> feat: Add sorted set put and fetch methods

momento-sdk/src/intTest/java/momento/sdk/SortedSetTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSortedSetGetRankResponse.java
Add sortedSetGetRank. This returns the rank of the given sorted set element.
Add generic code for executing a grpc function. This should cut down on boilerplate in the internal data client.
=> feat: Add sortedSetGetRank

momento-sdk/src/intTest/java/momento/sdk/SortedSetTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSortedSetGetScoreResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSortedSetGetScoresResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSortedSetIncrementScoreResponse.java
Add methods for getting the score of an element in a sorted set.
Add methods for getting the scores of multiple elements in a sorted set.
Add methods for incrementing the score of an element in a sorted set.
=> feat: add sortedSetGetScore, sortedSetGetScores, and sortedSetIncrementScore

momento-sdk/src/intTest/java/momento/sdk/SortedSetTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSortedSetRemoveElementResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheSortedSetRemoveElementsResponse.java
Add methods to remove an element from a sorted set.
Add methods to remove multiple elements from a sorted set.
=> feat: Add sortedSetRemoveElement and sortedSetRemoveElements

momento-sdk/src/intTest/java/momento/sdk/BaseTestClass.java, momento-sdk/src/intTest/java/momento/sdk/CacheClientTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheControlPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneClientSideTest.java, momento-sdk/src/intTest/java/momento/sdk/CacheDataPlaneTest.java, momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/intTest/java/momento/sdk/ListTest.java, momento-sdk/src/intTest/java/momento/sdk/SetTest.java, momento-sdk/src/intTest/java/momento/sdk/SortedSetTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsClient.java, momento-sdk/src/main/java/momento/sdk/ScsControlClient.java, momento-sdk/src/main/java/momento/sdk/ScsControlGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java
Make createCache, deleteCache, flushCache, listCaches, and the signing key methods async to match.
=> chore: Change control methods to be async

momento-sdk/src/main/java/momento/sdk/ScsDataClient.java
This PR corrects some of the sorted set names used internally.
=> chore: audit sorted set internal arguments

momento-sdk/src/main/java/momento/sdk/CacheClient.java
Update the Javadocs for the list methods.
Add Nullable and Nonnull annotations to all list method arguments.
=> chore: Update list method documentation.

momento-sdk/src/main/java/momento/sdk/CacheClient.java
Add null/nonnull annotations to the set collection methods
work towards https://github.com/momentohq/client-sdk-java/issues/245
=> chore: annotate set collection argument nullability

momento-sdk/src/main/java/momento/sdk/CacheClient.java
- docs: add dots
- docs: normalize casing of TTL
=> docs: normalize punctuation and casing

momento-sdk/src/intTest/java/momento/sdk/DictionaryTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryFetchResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryGetFieldResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryGetFieldsResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryIncrementResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryRemoveFieldResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionaryRemoveFieldsResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionarySetFieldResponse.java, momento-sdk/src/main/java/momento/sdk/messages/CacheDictionarySetFieldsResponse.java
Update the javadoc for the dictionary methods.
Update the javadoc for the dictionary responses.
Change the field/value/element language in the dictionary response getters.
Annotate the dictionary user-facing and internal methods with Nullable and Nonnull.
=> chore: Update the dictionary javadoc

.github/workflows/ci.yml, README.template.md, examples/lib/build.gradle.kts, examples/lib/src/main/java/momento/client/example/doc_examples/CheatSheet.java, examples/lib/src/main/java/momento/client/example/doc_examples/DocExamplesJavaAPIs.java, examples/lib/src/main/java/momento/client/example/doc_examples/ReadmeExample.java
Simplify readme and use a code snippet.
Add code snippets for the cheat sheet and docs examples.
=> feat: Add example code snippets that will populate the dev docs

examples/cache/src/main/java/momento/client/example/LoadGenerator.java
For https://github.com/momentohq/dev-eco-issue-tracker/issues/431
=> chore: update loadgen to be more specific for numberOfConcurrentRequests caveat

.github/workflows/ci.yml, examples/cache-with-aws/README.md, examples/cache-with-aws/src/main/java/momento/client/example/BasicExample.java, examples/cache/README.md, examples/cache/build.gradle.kts, examples/cache/src/main/java/momento/client/example/BasicExample.java, examples/cache/src/main/java/momento/client/example/BatchUtilsExample.java, examples/cache/src/main/java/momento/client/example/DictionaryExample.java, examples/cache/src/main/java/momento/client/example/ListExample.java, examples/cache/src/main/java/momento/client/example/LoadGenerator.java, examples/cache/src/main/java/momento/client/example/SetExample.java, examples/cache/src/main/java/momento/client/example/SortedSetExample.java, examples/cache/src/main/java/momento/client/example/advanced/WithDatabaseExample.java, examples/cache/src/main/java/momento/client/example/doc_examples/CheatSheet.java, examples/cache/src/main/java/momento/client/example/doc_examples/DocExamplesJavaAPIs.java, examples/cache/src/main/java/momento/client/example/doc_examples/ReadmeExample.java
Add examples for batch utils and rename auth token to API key
=> chore: add examples for batch utils and rename auth token to API key

examples/token/build.gradle.kts, examples/token/src/main/java/momento/client/example/docs_examples/DocExamplesJavaAPIs.java
- Add disposable-token example for docs
=> feat: add disposable-token example for docs

CONTRIBUTING.md
Update instruction from "auth token from CLI" to "api key from console"
=> chore: update instructions in contributing doc

momento-sdk/src/main/java/momento/sdk/PreviewStorageClient.java, momento-sdk/src/main/java/momento/sdk/responses/storage/GetResponse.java, momento-sdk/src/main/java/momento/sdk/responses/storage/StorageValue.java
Adds more documentation for storage response types, especially the get
response and storage value.
=> docs: document storage response types more thoroughly

momento-sdk/src/main/java/momento/sdk/ScsClientBase.java, momento-sdk/src/main/java/momento/sdk/ScsControlGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ScsDataGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ScsTokenGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/ScsTopicGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/StorageControlGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/StorageDataGrpcStubsManager.java, momento-sdk/src/main/java/momento/sdk/UserHeaderInterceptor.java
- https://github.com/momentohq/dev-eco-issue-tracker/issues/891
- https://github.com/momentohq/client-sdk-java/issues/372
=> feat: onetime headers for agent and runtime-version

momento-sdk/src/main/java/momento/sdk/ClientBase.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java
Create a batch version of the existing generic execute grpc function and move setBatch and getBatch to it.
Switch the rest of the scalar calls to use the existing generic grpc execution function. This provides a single point where we can do things like limit concurrent calls.
=> chore: Generify the scalar cache functions

momento-sdk/src/intTest/java/momento/sdk/CacheClientTest.java, momento-sdk/src/main/java/momento/sdk/CacheClient.java, momento-sdk/src/main/java/momento/sdk/ScsDataClient.java, momento-sdk/src/main/java/momento/sdk/responses/cache/ttl/DecreaseTtlResponse.java, momento-sdk/src/main/java/momento/sdk/responses/cache/ttl/IncreaseTtlResponse.java
Implements increase- and decrease-ttl, adds integration tests, and
adds documentation.
=> feat: implement increase and decrease ttl

momento-sdk/build.gradle.kts, momento-sdk/src/intTest/java/momento/sdk/retry/BaseCacheRetryTestClass.java, momento-sdk/src/intTest/java/momento/sdk/retry/FixedCountRetryStrategyIntegTest.java, momento-sdk/src/intTest/java/momento/sdk/retry/FixedDelayRetryStrategyIntegTest.java, momento-sdk/src/intTest/java/momento/sdk/retry/TestRetryMetricsCollectorTest.java, momento-sdk/src/intTest/java/momento/sdk/retry/TestRetryMetricsMiddlewareTest.java, momento-sdk/src/intTest/java/momento/sdk/retry/utils/TestRetryMetricsMiddlewareRequestHandler.java, momento-sdk/src/main/java/momento/sdk/ScsDataGrpcStubsManager.java
- Adds automated retry tests for `FixedCountRetryStrategy` and `FixedDelayRetryStrategy`
https://github.com/momentohq/dev-eco-issue-tracker/issues/1113
=> feat: add automated retry tests

.github/workflows/retry-tests.yml, Makefile, docker-compose.yml, momento-sdk/build.gradle.kts
- Add automated retry tests to ci job
https://github.com/momentohq/dev-eco-issue-tracker/issues/1113
=> feat: add automated retry tests to ci

examples/leaderboard/src/main/java/momento/client/example/doc_examples/DocExamplesJavaAPIs.java
- Add `getCompetitionRank` to doc examples
https://github.com/momentohq/dev-eco-issue-tracker/issues/1138
=> fix: add getCompetitionRank doc example
